### ISSUE TITLE
Cannot use Parameters of plugin

### ISSUE THREAD

**Issue by harryleesan** [SumoLogic/logstash-output-sumologic#12]
Logstash version: 5.6.3+

When adding parameters other than `url` and `format`, (such as `source_category`, `source_name` and `source_host`, an error is the logstash logs is shown:

```bash
[ERROR] 2018-01-18 14:16:15.914 [Ruby-0-Thread-3: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/task.rb:22] sumologic - Unknown setting 'source_host' for sumologic
```

**Comment by mrballcb** [comment]
I found the same thing in 5.6.5 (elastic.co's official docker image, 5.6.5).  It looks like running `logstash-plugin install logstash-output-sumologic` does not install the latest release.

```
bash-4.2$ logstash -V
logstash 5.6.5
bash-4.2$ logstash-plugin install logstash-output-sumologic
Validating logstash-output-sumologic
Installing logstash-output-sumologic
Installation successful
bash-4.2$ logstash-plugin list --installed --verbose | grep sumo
logstash-output-sumologic (1.0.4)
```

I'm still experimenting to see if I can get it to install a later version or if it requires a local build of the gem to make it work.

**Comment by bin3377** [comment]
Looks like the rubygems has some inconsistency. I have put a new minor build (`1.1.3`) as latest one and test it works now on the latest logstash
```
00:15 # logstash -V
logstash 6.2.2
00:15 # logstash-plugin list --installed --verbose | grep sumologic
logstash-output-sumologic (1.1.3)
```
Could you please try it again?

**Comment by mrballcb** [comment]
@bin3377 Whatever you did, it seems to have fixed this for me, even on the older logstash docker image:

```
$ docker run --rm -it docker.elastic.co/logstash/logstash:5.6.5 /bin/bash
bash-4.2$ logstash -V
logstash 5.6.5
bash-4.2$ logstash-plugin list --installed --verbose | grep sumologic
bash-4.2$ logstash-plugin install logstash-output-sumologic
Validating logstash-output-sumologic
Installing logstash-output-sumologic
Installation successful
bash-4.2$ logstash-plugin list --installed --verbose | grep sumologic
logstash-output-sumologic (1.1.3)
bash-4.2$
```

Fantastic job and thanks!

**Comment by bin3377** [comment]
Thanks for the confirming. Will close this issue.
