### ISSUE TITLE
Variables in output is not working 

### ISSUE THREAD

**Issue by zamirajaupaj** [SumoLogic/logstash-output-sumologic#35]
hello,
i'm trying to use this plugin, but i have an issue: is not working value in output. Sumo logic create the resources with name: prod/%{logGroupName} but not with name prod/aws/lambda/zamira
in local i have this output:

```
{
   "@timestamp" => 2019-03-18T14:43:33.030Z,
  "message" => "myjson",
  "logGroupName" => "/aws/lambda/zamira",
   "id" => "/aws/lambda/zamira",
 }
```

my configuration file is:

```
filter {
  if [type] == "kinesis" {
    json {
      source => "message"
      add_field => { "id" => "%{logGroupName}" }
    }
    
    mutate {
      replace => { "message" => "My new message" }}
    }
  }
}

output {
  if [accountId] == "" {
    sumologic {
      format => "%{@json}"
      source_category => "prod/%{logGroupName}"
      url => "https://endpoint1.collection.eu.sumologic.com/receiver/v1/http/xxxxxxxxxxxxx"
    }
  }
} 

```

**Comment by mk811** [comment]
I have same issue. I've tried to create dynamic source_category using metadata or value in some fields but those aren't successul.
Example code is described below, which is pretty same with zamirajaupaj's code.
```logstash
output {
  if [accountId] == "" {
    sumologic {
      format => "%{@json}"
      source_category => "%{[@metadata][env]}"
      url => "https://endpoint1.collection.eu.sumologic.com/receiver/v1/http/xxxxxxxxxxxxx"
    }
  }
```

**Comment by bin3377** [comment]
currently `%{}` interpreter is; n78

**Comment by bin3377** [comment]
Current the `%{}` is not supported in header tags like `source_name`, `source_category`, etc.

**Comment by bin3377** [comment]
https://github.com/SumoLogic/logstash-output-sumologic/issues/33
