### ISSUE TITLE
Logstash stopped sending log data for certain amount of time.

### ISSUE THREAD

**Issue by mk811** [SumoLogic/logstash-output-sumologic#38]
This is might be related to #27.

## Bckground
I'm sending log data to Sumologic via Logstash.
Logs are collected by journalbeat, metricbeat, and filebeat.
Since we collect logs of Kubernetes, the amount of logs sent to Sumo is 1.0 GB.

## Issue
Logstash stopped sending logs to Sumologic.
But not stoped all logs but they lost significant numbers of logs.
The images below show my situation. They occasionally lost logs of some categories. However, they keep sending other logs. 

**[logs collected by journalbeat (docker container log and server's journal log)]**  
<img width="1142" alt="スクリーンショット 2019-04-24 23 54 31" src="https://user-images.githubusercontent.com/32785388/56670568-08f47980-66ee-11e9-89cc-bdbd0f257284.png">

**[Metricbeat Log]**
<img width="1130" alt="スクリーンショット 2019-04-24 23 58 15" src="https://user-images.githubusercontent.com/32785388/56670579-0f82f100-66ee-11e9-9621-361c410791f4.png">

## Current Solution
When we faced thiss issue, we restart logstash container. Then it'll start sending logs again.

## Expected
The logs must be sent to Sumo stably.
Never lost of log data.

## Note,
My logstash configuration is described below.

```
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/http/...(token)..."
        format => "%{@json}"
        source_category => "prod/server/ocp/logs"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 
        pile_max => 1024000 
        queue_max => 4096 
        sender_max => 10 
      }
```

**Comment by bin3377** [comment]
Thanks for the reporting. issue #27 was fixed in 1.2.12. Please make sure using the latest version of plugin.
If the problem cannot be resolved, I may need more information to identify what's the problem.

1. logstash log file when issue happens (if possible, enable debugging log). Refer to [this page](https://www.elastic.co/guide/en/logstash/current/logging.html) for log file location and how to enable debugging log 
2. Any suspicious on the resource consumption when the issue happens (CPU/Memory/Disk/Network traffic)
3. collector and source id (you can get them from "Manage Data" -> "Collection" page. navigate to the HTTP source and click the small (i) icon on the right side of the source row)

**Comment by mk811** [comment]
Thank you for quick response! I think I'm using latest one.
See below. 
```
# bin/logstash-plugin list --verbose logstash-output-sumologic
logstash-output-sumologic (1.2.2)

# bin/logstash --version                                      
logstash 6.6.2
```

After I restarted logstash container with log level=warn, I found suspicious message as below.
```
[2019-04-24T17:40:13,140][WARN ][logstash.pipeline        ] CAUTION: Recommended inflight events max exceeded! Logstash will run with up to 12000 events in memory in your current configuration. If your message sizes are large this may cause instability with the default heap size. Please consider setting a non-standard heap size, changing the batch size (currently 3000), or changing the number of pipeline workers (currently 4) {:pipeline_id=>"main", :thread=>"#<Thread:0x60d66d8f run>"}
```

So I guess I need to increase  heap size and batch size?
I allocated 4GB of memory to Logstash JVM though.
```
## JVM configuration

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms4g
-Xmx4g
```

Note, My VM's memory and CPU are quite free
```
# vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free             buff     cache          si   so    bi    bo   in   cs   us  sy  id   wa  st
 1  0      0       2545892   3548   4333488    0    0      8     9     3   11    2   1     97  0    0
```
and my disk is also free (9GB available for logstash container)

**Comment by mk811** [comment]
Note, the spec of my VM is:
Azure Standard_D2s_v3, which has 8GB memory and 4vCPU.

**Comment by bin3377** [comment]
it's more or less relate to the (logstash performance tuning)[https://www.elastic.co/guide/en/logstash/current/tuning-logstash.html]
https://discuss.elastic.co/t/what-kind-of-size-is-better-to-set-logstash-pipline/95112

Generally speaking a larger heap size on JVM, smaller batch size and more pipeline workers maybe helpful. Another approach is using a replica set of Logstash to balance the load if your container is  working on k8s

**Comment by mk811** [comment]
Hmm. The changing to smaller batch size didn't solve my trouble.
My configuration of Logstash is:
- Heap: -Xms4g,  -Xmx4g
- Worker: 4cpu
- batch: 500
- delay: 20

By the way, I have multiple `sumoloigc` blocks in output directive to switch sourceCategories, is there any concerns on this configuration?

```
output {
  if [fields][env] == "prod" {
    if [fields][source_type] == "server" and [fields][service] == "shared" {
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
        format => "%{@json}"
        source_category => "prod/server/shared/logs"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
        pile_max => 1024000 # one request can hold up to 1000KB of data
        queue_max => 4096 # up to 4096 requests can be queued in memory
        sender_max => 10 # use up to 10 http client working parallel
      }
    } else if [fields][source_type] == "server" and [fields][service] == "ocp" {
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
        format => "%{@json}"
        source_category => "prod/server/ocp/logs"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
        pile_max => 1024000 # one request can hold up to 1000KB of data
        queue_max => 4096 # up to 4096 requests can be queued in memory
        sender_max => 10 # use up to 10 http client working parallel
      }
    } else if [fields][source_type] == "container" and [fields][service] == "shared" {
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
        format => "%{@json}"
        source_category => "prod/container/shared/logs"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
        pile_max => 1024000 # one request can hold up to 1000KB of data
        queue_max => 4096 # up to 4096 requests can be queued in memory
        sender_max => 10 # use up to 10 http client working parallel

      }
    } else if [fields][source_type] == "container" and [fields][service] == "ocp" {
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
        format => "%{@json}"
        source_category => "prod/container/ocp/logs"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
        pile_max => 1024000 # one request can hold up to 1000KB of data
        queue_max => 4096 # up to 4096 requests can be queued in memory
        sender_max => 10 # use up to 10 http client working parallel
      }
    } else {
      sumologic {
        url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
        format => "%{@json}"
        source_category => "prod/missing/missing/missing"
        source_host => "sumo-logstash"
        cookies => false
        compress => true
        compress_encoding => "gzip"
        interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
        pile_max => 1024000 # one request can hold up to 1000KB of data
        queue_max => 4096 # up to 4096 requests can be queued in memory
        sender_max => 10 # use up to 10 http client working parallel
      }
    }
  } else {
    sumologic {
      url => "https://collectors.jp.sumologic.com/receiver/v1/xxx"
      format => "%{@json}"
      source_category => "missing/missing/missing/missing"
      source_host => "sumo-logstash"
      cookies => false
      compress => true
      compress_encoding => "gzip"
      interval => 5 # one request can hold up to 5 sec of events, if 0, means every event in a request 
      pile_max => 1024000 # one request can hold up to 1000KB of data
      queue_max => 4096 # up to 4096 requests can be queued in memory
      sender_max => 10 # use up to 10 http client working parallel
    }  
  } 
}
```

**Comment by bin3377** [comment]
with this configuration each output plugin will use up to 4G mem. but if you didn't get any OOM exception in log it's probably fine.
Is there any error/exception in log or maybe you can enable the debug log for some details? (it will take very large disk space though)

**Comment by mk811** [comment]
I poked around this and found interesting phenomena.
Sumologic successfully received logs from Logstash but showed logs delayed for 9 hours, which is the time difference of Japan time (UTC +9).

The screenshot taken at  2019-04-24 11/54 PM (Japan Time). The logs weren't shown
<img width="1142" alt="ScreenShot 2019-04-24 23 54 31" src="https://user-images.githubusercontent.com/32785388/56705556-5acbec80-674c-11e9-845b-e0985d9561c2.png">

The screenshot taken at  2019-04-25 11/17 AM (Japan Time). The logs came out.
<img width="1154" alt="ScreenShot 2019-04-25 11 17 03" src="https://user-images.githubusercontent.com/32785388/56705559-5e5f7380-674c-11e9-8a92-044cf5d44e0e.png">

This screen shot shows the maximum time differences  between Receipt Time and Timestamp of logs within 10 minutes. It must be close to 0 but we have more than 9 hours differences, which is not expected. Do you have any ideas to fix this?
<img width="1425" alt="スクリーンショット 2019-04-25 11 54 09" src="https://user-images.githubusercontent.com/32785388/56706702-e9db0380-6750-11e9-9d99-48a17b302a07.png">

I think this is out of scope of your plugin so I will post this to Sumo Dojo as well.

**Comment by bin3377** [comment]
It's very likely your ingestion is throttled. You can confirm it from Sumo Dojo or support channel

**Comment by astencel-sumo** [comment]
I will close this issue if there's no further comments.
