### ISSUE TITLE
Bundler could not find compatible versions for gem logstash-core

### ISSUE THREAD

**Issue by zakst** [SumoLogic/logstash-output-sumologic#6]
I am on an `elasticbeanstalk` instance.

The `Getting Started` steps all work great till `Step 4`. First change was going to `/opt/logstash/bin/` to run `plugin`.

And it gave me the following error

`Validating logstash-output-sumologic/logstash-output-sumologic-1.0.4.gem
Installing logstash-output-sumologic
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.1.3)
  In Gemfile:
    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.2.1) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-output-sumologic (= 1.0.4) java depends on
      logstash-core-plugin-api (~> 2.0) java depends on
        logstash-core (= 5.0.0.alpha3.snapshot4) java

    logstash-core (= 2.1.3) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

any one had a similar issue?

**Comment by bin3377** [comment]
Tested with the latest gem (1.0.4) and logstash 5.5.1 (on mac with `brew install logstash`), the steps are just working fine.
But someone do facing problem when migration from logstash 2.x to 5.x because some plug-in has dependency issue. Maybe you can give it a try now?

**Comment by bin3377** [comment]
with logstash 5.1.1, you can try with following dependencies' versions, at least it works for me (Mac OSX)
```
jruby 9.1.7.0
gem install logstash-core-plugin-api -v 2.1.27
gem install logstash-codec-plain -v 3.0.4
gem install jar-dependencies -v 0.3.11
bundle update
```

**Comment by mPanasiewicz** [comment]
The same issue with logstash-input-googleanalytics-1.0.0
