### ISSUE TITLE
Collector returns 502

### ISSUE THREAD

**Issue by im-dim** [SumoLogic/logstash-output-sumologic#65]
We are getting a lot of intermittent 502 errors like below but some data IS coming to Sumo.
Is there a limit on ingest requests per minute or something?
How can we be sure that we get _all_ data?

[2021-09-02T10:57:57,724][ERROR][logstash.outputs.sumologic][sumo_out] request rejected {:token=>26, :code=>502, :headers=>{"X-Sumo-Client"=>"logstash-output-sumologic", "X-Sumo-Category"=>"elastiflow", "X-Sumo-Host"=>"ct-centos001", "X-Sumo-Name"=>"elastiflow", "Content-Type"=>"text/plain"}, :contet=>"{\"event\":{\"type\":\"net"}

**Comment by astencel-sumo** [comment]
Hi @im-dim, Sumo Logic returns the standard HTTP code [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) `Too Many Requests` if you hit a request limit. The `502` errors mean a different kind of error on the server side. I recommend you reach to Sumo Logic customer support for this.

**Comment by im-dim** [comment]
The code we received is 502. not 429.
Please advise...

**Comment by astencel-sumo** [comment]
Sorry if I wasn't clear enough. The `502` error code indicates a server issue, other than request limit. Judging by the data you provided, you are NOT being throttled and request limit is NOT the issue. The `502` error means there is an issue on the server side, but the nature of the issue is unknown. As I wrote above, I recommend to reach out to Sumo Logic support to find out more.

**Comment by im-dim** [comment]
Thank you Andrzej. Much appreciated. Appology for confusion.


Thanks,
Dmitriy.

From: Andrzej Stencel ***@***.***>
Reply-To: SumoLogic/logstash-output-sumologic ***@***.***>
Date: Friday, September 10, 2021 at 8:55 AM
To: SumoLogic/logstash-output-sumologic ***@***.***>
Cc: Dmitriy Vagner ***@***.***>, Mention ***@***.***>
Subject: Re: [SumoLogic/logstash-output-sumologic] Collector returns 502 (#65)


Sorry if I wasn't clear enough. The 502 error code indicates a server issue, other than request limit. Judging by the data you provided, you are NOT being throttled and request limit is NOT the issue. The 502 error means there is an issue on the server side, but the nature of the issue is unknown. As I wrote above, I recommend to reach out to Sumo Logic support to find out more.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SumoLogic_logstash-2Doutput-2Dsumologic_issues_65-23issuecomment-2D916882835&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=o8HCp8s27O2pQrxUn-zTzukq2lTZz1ink-akiUoNFZg&m=D22YiEkKYjDMMY8lRax7hap80xZ87rI9XeWF6mu3CaM&s=uwqSVWBjVW25bzwxu8zpX8tGYn_HkGBcP3zlghJFadk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APZ6MZUNU3IW4CPCRLG7GILUBH54XANCNFSM5DSQKBIA&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=o8HCp8s27O2pQrxUn-zTzukq2lTZz1ink-akiUoNFZg&m=D22YiEkKYjDMMY8lRax7hap80xZ87rI9XeWF6mu3CaM&s=vTIJCGYkWiFhxd1hayxxSa2kOUDTZFS6CRfKJ1kRIsU&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=o8HCp8s27O2pQrxUn-zTzukq2lTZz1ink-akiUoNFZg&m=D22YiEkKYjDMMY8lRax7hap80xZ87rI9XeWF6mu3CaM&s=9Kmq3anGRw8eFqY0yWXEXEFiiZcBRPkKhLD43mpd4uY&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=o8HCp8s27O2pQrxUn-zTzukq2lTZz1ink-akiUoNFZg&m=D22YiEkKYjDMMY8lRax7hap80xZ87rI9XeWF6mu3CaM&s=VEhUQSLBrRpJsE7uDEi1RGoAUHgVhLtjcJ94lzf0YAs&e=>.

This message may contain Confidential information intended solely for the use of the addressee(s) named above. Any disclosure or distribution to or copy or use by others of Confidential or Restricted information contained in this message is strictly prohibited. Please notify the sender immediately by e-mail if you have received this e-mail in error and then delete this e-mail from your system. Investment Metrics has logged this e-mail for archival purposes and it may be reviewed by parties at Investment Metrics other than those named in the message header in the course of business. This message does not necessarily constitute an official representation of Investment Metrics. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Investment Metrics
