### ISSUE TITLE
Interval argument is using the wrong units

### ISSUE THREAD

**Issue by robchahin** [SumoLogic/logstash-output-sumologic#9]
Per https://github.com/SumoLogic/logstash-output-sumologic/blob/master/lib/logstash/outputs/sumologic.rb#L157, `interval` is being compared to `Time`, which uses seconds for arithmetic.

Per https://github.com/SumoLogic/logstash-output-sumologic/blame/master/README.md#L70, the docs ask for the `interval` argument to be supplied in milliseconds.

One of the two should change - preferably the docs so existing implementations that are working around this don't break.

Behavior can be checked easily:

`puts "Now: #{Time.now}\n5 Seconds Ago: #{Time.now-5}"`
`Now: 2017-12-20 12:30:57 -0800`
`5 Seconds Ago: 2017-12-20 12:30:52 -0800`

**Comment by bin3377** [comment]
Thanks for reporting the issue! The document is fixed
